Repository DDD-Community/DDD-8-Web2-Server, pull requests merged in 2023-01, with the labels that each got.

#19 hotfix(SecurityConfiguration): Cors 특정 URI 허용
  src/main/java/ddd/caffeine/ratrip/common/configuration/SecurityConfiguration.java
Labels: hotfix

#11 장소 상세 검색 API
  .github/workflows/ci.yml
  build.gradle
  src/main/java/ddd/caffeine/ratrip/common/configuration/FeignConfiguration.java
  src/main/java/ddd/caffeine/ratrip/common/exception/ExceptionInformation.java
  src/main/java/ddd/caffeine/ratrip/common/util/FeignErrorDecoder.java
  src/main/java/ddd/caffeine/ratrip/common/util/FeignResponseEncoder.java
  src/main/java/ddd/caffeine/ratrip/module/feign/domain/place/kakao/PlaceKakaoData.java
  src/main/java/ddd/caffeine/ratrip/module/feign/domain/place/naver/ImageNaverModel.java
  src/main/java/ddd/caffeine/ratrip/module/place/PlaceService.java
  src/main/java/ddd/caffeine/ratrip/module/place/feign/PlaceFeignService.java
  src/main/java/ddd/caffeine/ratrip/module/place/feign/kakao/KakaoFeignClient.java
  src/main/java/ddd/caffeine/ratrip/module/place/feign/kakao/model/KakaoFeignMetaData.java
  src/main/java/ddd/caffeine/ratrip/module/place/feign/kakao/model/PlaceKakaoData.java
  src/main/java/ddd/caffeine/ratrip/module/place/feign/kakao/model/PlaceKakaoModel.java
  src/main/java/ddd/caffeine/ratrip/module/place/feign/naver/NaverFeignClient.java
  src/main/java/ddd/caffeine/ratrip/module/place/feign/naver/model/ImageItem.java
  src/main/java/ddd/caffeine/ratrip/module/place/feign/naver/model/ImageNaverModel.java
  src/main/java/ddd/caffeine/ratrip/module/place/model/Address.java
  src/main/java/ddd/caffeine/ratrip/module/place/model/Category.java
  src/main/java/ddd/caffeine/ratrip/module/place/model/Location.java
  src/main/java/ddd/caffeine/ratrip/module/place/model/Place.java
  src/main/java/ddd/caffeine/ratrip/module/place/model/Region.java
  src/main/java/ddd/caffeine/ratrip/module/place/model/address/Address.java
  src/main/java/ddd/caffeine/ratrip/module/place/model/address/Region.java
  src/main/java/ddd/caffeine/ratrip/module/place/presentation/PlaceController.java
  src/main/java/ddd/caffeine/ratrip/module/place/presentation/dto/PlaceDetailsResponseDto.java
  src/main/java/ddd/caffeine/ratrip/module/place/presentation/dto/PlaceSearchModel.java
  src/main/java/ddd/caffeine/ratrip/module/place/repository/PlaceRepository.java
  src/main/java/ddd/caffeine/ratrip/module/place/service/PlaceService.java
  src/main/java/ddd/caffeine/ratrip/module/place/service/PlaceValidator.java
  src/main/resources/application-test.yml
  src/main/resources/application.yml
  src/test/java/ddd/caffeine/ratrip/TestConfig.java
  src/test/java/ddd/caffeine/ratrip/module/place/model/PlaceTest.java
  src/test/java/ddd/caffeine/ratrip/module/place/repository/PlaceRepositoryTest.java
  src/test/java/ddd/caffeine/ratrip/module/place/service/PlaceValidatorTest.java
  src/test/resources/application.yml
Labels: enhancement

#18 장소 상세 검색 API - UUID 로 읽어오기
  src/main/java/ddd/caffeine/ratrip/common/exception/ExceptionInformation.java
  src/main/java/ddd/caffeine/ratrip/module/place/presentation/PlaceController.java
  src/main/java/ddd/caffeine/ratrip/module/place/service/PlaceService.java
  src/main/java/ddd/caffeine/ratrip/module/place/service/PlaceValidator.java
  src/test/java/ddd/caffeine/ratrip/module/place/service/PlaceValidatorTest.java
Labels: enhancement

#26 추천 장소 API 응답값 중 좌표 추가
  src/main/java/ddd/caffeine/ratrip/module/place/presentation/dto/PopularPlaceModel.java
Labels: enhancement

#29 장소 추천 초기 데이터 INSERT
  src/main/java/ddd/caffeine/ratrip/module/place/model/Place.java
  src/main/resources/application-dev.yml
  src/main/resources/application-test.yml
  src/main/resources/data-develop.sql
  src/test/java/ddd/caffeine/ratrip/module/place/service/PlaceValidatorTest.java
Labels: enhancement

#23 Feat/manage key safely
  src/main/java/ddd/caffeine/ratrip/common/configuration/SecretPropertiesConfiguration.java
  src/main/java/ddd/caffeine/ratrip/common/secret/SecretKeyManager.java
  src/main/java/ddd/caffeine/ratrip/module/auth/application/KakaoAuthService.java
  src/main/java/ddd/caffeine/ratrip/module/place/feign/PlaceFeignService.java
  src/main/resources/application-dev.yml
  src/main/resources/application-secret.yml
Labels: proposal

#27 Feat/validate requestparam in controller
  src/main/java/ddd/caffeine/ratrip/common/validator/RequestDataValidator.java
  src/main/java/ddd/caffeine/ratrip/module/place/feign/PlaceFeignService.java
  src/main/java/ddd/caffeine/ratrip/module/place/feign/kakao/model/PlaceKakaoModel.java
  src/main/java/ddd/caffeine/ratrip/module/place/model/ThirdPartyDetailSearchOption.java
  src/main/java/ddd/caffeine/ratrip/module/place/model/ThirdPartySearchOption.java
  src/main/java/ddd/caffeine/ratrip/module/place/presentation/PlaceController.java
  src/main/java/ddd/caffeine/ratrip/module/place/presentation/dto/detail/PlaceDetailsByThirdPartyRequestDto.java
  src/main/java/ddd/caffeine/ratrip/module/place/presentation/dto/detail/PlaceDetailsByUUIDRequestDto.java
  src/main/java/ddd/caffeine/ratrip/module/place/presentation/dto/detail/PlaceDetailsResponseDto.java
  src/main/java/ddd/caffeine/ratrip/module/place/presentation/dto/popular/PopularPlaceModel.java
  src/main/java/ddd/caffeine/ratrip/module/place/presentation/dto/popular/PopularPlaceResponseDto.java
  src/main/java/ddd/caffeine/ratrip/module/place/presentation/dto/search/PlaceSearchModel.java
  src/main/java/ddd/caffeine/ratrip/module/place/presentation/dto/search/PlaceSearchRequestDto.java
  src/main/java/ddd/caffeine/ratrip/module/place/presentation/dto/search/PlaceSearchResponseDto.java
  src/main/java/ddd/caffeine/ratrip/module/place/service/PlaceService.java
  src/test/java/ddd/caffeine/ratrip/common/validator/RequestDataValidatorTest.java
Labels: proposal

#32 [!BREAKING CHANGE] 장소추천 API -> 지역 기반 장소 API
  src/main/java/ddd/caffeine/ratrip/common/util/QuerydslUtils.java
  src/main/java/ddd/caffeine/ratrip/module/place/presentation/PlaceController.java
  src/main/java/ddd/caffeine/ratrip/module/place/presentation/dto/PlaceInRegionModel.java
  src/main/java/ddd/caffeine/ratrip/module/place/presentation/dto/PlaceInRegionResponseDto.java
  src/main/java/ddd/caffeine/ratrip/module/place/presentation/dto/popular/PopularPlaceResponseDto.java
  src/main/java/ddd/caffeine/ratrip/module/place/repository/PlaceQueryRepository.java
  src/main/java/ddd/caffeine/ratrip/module/place/repository/PlaceQueryRepositoryImpl.java
  src/main/java/ddd/caffeine/ratrip/module/place/service/PlaceService.java
  src/main/resources/application-dev.yml
  src/main/resources/data-develop.sql
  src/test/java/ddd/caffeine/ratrip/module/place/repository/PlaceRepositoryTest.java
Labels: enhancement

#39 hotfix : 장소 검색 API 응답값 필드 추가
  src/main/java/ddd/caffeine/ratrip/module/place/feign/kakao/model/PlaceKakaoModel.java
  src/main/java/ddd/caffeine/ratrip/module/place/presentation/dto/search/PlaceSearchResponseDto.java
Labels: enhancement

#25 여행 일정 도메인 설계
  src/main/java/ddd/caffeine/ratrip/common/model/Region.java
  src/main/java/ddd/caffeine/ratrip/module/place/model/Address.java
  src/main/java/ddd/caffeine/ratrip/module/place/model/Place.java
  src/main/java/ddd/caffeine/ratrip/module/place/presentation/dto/search/PlaceSearchRequestDto.java
  src/main/java/ddd/caffeine/ratrip/module/place/repository/PlaceQueryRepository.java
  src/main/java/ddd/caffeine/ratrip/module/place/repository/PlaceQueryRepositoryImpl.java
  src/main/java/ddd/caffeine/ratrip/module/place/service/PlaceService.java
  src/main/java/ddd/caffeine/ratrip/module/travel_plan/DaySchedule.java
  src/main/java/ddd/caffeine/ratrip/module/travel_plan/DaySchedulePlace.java
  src/main/java/ddd/caffeine/ratrip/module/travel_plan/TravelPlan.java
  src/main/java/ddd/caffeine/ratrip/module/travel_plan/TravelPlanUser.java
  src/main/resources/data-develop.sql
  src/test/java/ddd/caffeine/ratrip/module/place/model/PlaceTest.java
  src/test/java/ddd/caffeine/ratrip/module/place/model/RegionTest.java
  src/test/java/ddd/caffeine/ratrip/module/place/repository/PlaceRepositoryTest.java
Labels: enhancement

#40 URI 리팩토링 및 검증 Custom 어노테이션 [주안님 피드백]
  src/main/java/ddd/caffeine/ratrip/common/exception/GlobalExceptionHandler.java
  src/main/java/ddd/caffeine/ratrip/module/place/presentation/PlaceController.java
  src/main/java/ddd/caffeine/ratrip/module/place/presentation/dto/detail/PlaceDetailsByThirdPartyRequestDto.java
  src/test/java/ddd/caffeine/ratrip/module/place/presentation/PlaceControllerTest.java
Labels: enhancement

#46 여행 일정 읽기 API
  src/main/java/ddd/caffeine/ratrip/common/exception/ExceptionInformation.java
  src/main/java/ddd/caffeine/ratrip/common/exception/domain/TravelPlanException.java
  src/main/java/ddd/caffeine/ratrip/module/place/application/BookmarkService.java
  src/main/java/ddd/caffeine/ratrip/module/place/application/BookmarkValidator.java
  src/main/java/ddd/caffeine/ratrip/module/place/domain/repository/bookmark/BookmarkQueryRepository.java
  src/main/java/ddd/caffeine/ratrip/module/place/domain/repository/bookmark/BookmarkQueryRepositoryImpl.java
  src/main/java/ddd/caffeine/ratrip/module/place/domain/repository/dao/BookMarkPlaceDao.java
  src/main/java/ddd/caffeine/ratrip/module/place/presentation/dto/bookmark/BookmarksResponseDto.java
  src/main/java/ddd/caffeine/ratrip/module/travel_plan/application/DaySchedulePlaceService.java
  src/main/java/ddd/caffeine/ratrip/module/travel_plan/application/DayScheduleService.java
  src/main/java/ddd/caffeine/ratrip/module/travel_plan/application/TravelPlanService.java
  src/main/java/ddd/caffeine/ratrip/module/travel_plan/application/TravelPlanUserService.java
  src/main/java/ddd/caffeine/ratrip/module/travel_plan/domain/TravelPlan.java
  src/main/java/ddd/caffeine/ratrip/module/travel_plan/domain/TravelPlanUser.java
  src/main/java/ddd/caffeine/ratrip/module/travel_plan/domain/repository/TravelPlanQueryRepository.java
  src/main/java/ddd/caffeine/ratrip/module/travel_plan/domain/repository/TravelPlanRepository.java
  src/main/java/ddd/caffeine/ratrip/module/travel_plan/domain/repository/TravelPlanUserQueryRepository.java
  src/main/java/ddd/caffeine/ratrip/module/travel_plan/domain/repository/TravelPlanUserRepository.java
  src/main/java/ddd/caffeine/ratrip/module/travel_plan/domain/repository/dao/DaySchedulePlaceDao.java
  src/main/java/ddd/caffeine/ratrip/module/travel_plan/domain/repository/dao/LocalDateDao.java
  src/main/java/ddd/caffeine/ratrip/module/travel_plan/domain/repository/day_schedule/DaySchedulePlaceQueryRepository.java
  src/main/java/ddd/caffeine/ratrip/module/travel_plan/domain/repository/day_schedule/DaySchedulePlaceRepository.java
  src/main/java/ddd/caffeine/ratrip/module/travel_plan/domain/repository/day_schedule/DayScheduleQueryRepository.java
  src/main/java/ddd/caffeine/ratrip/module/travel_plan/domain/repository/day_schedule/DayScheduleRepository.java
  src/main/java/ddd/caffeine/ratrip/module/travel_plan/domain/repository/day_schedule/implementation/DaySchedulePlaceQueryRepositoryImpl.java
  src/main/java/ddd/caffeine/ratrip/module/travel_plan/domain/repository/day_schedule/implementation/DayScheduleQueryRepositoryImpl.java
  src/main/java/ddd/caffeine/ratrip/module/travel_plan/domain/repository/implementation/TravelPlanQueryRepositoryImpl.java
  src/main/java/ddd/caffeine/ratrip/module/travel_plan/domain/repository/implementation/TravelPlanUserQueryRepositoryImpl.java
  src/main/java/ddd/caffeine/ratrip/module/travel_plan/presentation/DayScheduleController.java
  src/main/java/ddd/caffeine/ratrip/module/travel_plan/presentation/TravelPlanController.java
  src/main/java/ddd/caffeine/ratrip/module/travel_plan/presentation/dto/TravelPlanInitRequestDto.java
  src/main/java/ddd/caffeine/ratrip/module/travel_plan/presentation/dto/TravelPlanInitResponseDto.java
  src/main/java/ddd/caffeine/ratrip/module/travel_plan/presentation/dto/TravelPlanResponseDto.java
  src/main/java/ddd/caffeine/ratrip/module/travel_plan/presentation/dto/day_schedule/DaySchedulePlaceDto.java
  src/main/java/ddd/caffeine/ratrip/module/travel_plan/presentation/dto/day_schedule/DayScheduleResponseDto.java
  src/test/java/ddd/caffeine/ratrip/module/travel_plan/repository/DayScheduleRepositoryTest.java
Labels: enhancement

#50 일정 장소 추가 & 장소 순서 편집 & 전체 일정 불러오기
  src/main/java/ddd/caffeine/ratrip/common/exception/ExceptionInformation.java
  src/main/java/ddd/caffeine/ratrip/common/exception/domain/DayScheduleException.java
  src/main/java/ddd/caffeine/ratrip/module/place/application/BookmarkService.java
  src/main/java/ddd/caffeine/ratrip/module/place/application/PlaceService.java
  src/main/java/ddd/caffeine/ratrip/module/place/presentation/PlaceController.java
  src/main/java/ddd/caffeine/ratrip/module/travel_plan/application/DaySchedulePlaceService.java
  src/main/java/ddd/caffeine/ratrip/module/travel_plan/application/DayScheduleService.java
  src/main/java/ddd/caffeine/ratrip/module/travel_plan/application/DayScheduleValidator.java
  src/main/java/ddd/caffeine/ratrip/module/travel_plan/application/TravelPlanService.java
  src/main/java/ddd/caffeine/ratrip/module/travel_plan/application/TravelPlanUserService.java
  src/main/java/ddd/caffeine/ratrip/module/travel_plan/domain/DaySchedule.java
  src/main/java/ddd/caffeine/ratrip/module/travel_plan/domain/DayScheduleAccessOption.java
  src/main/java/ddd/caffeine/ratrip/module/travel_plan/domain/DaySchedulePlace.java
  src/main/java/ddd/caffeine/ratrip/module/travel_plan/domain/TravelPlanAccessOption.java
  src/main/java/ddd/caffeine/ratrip/module/travel_plan/domain/repository/TravelPlanUserQueryRepository.java
  src/main/java/ddd/caffeine/ratrip/module/travel_plan/domain/repository/dao/DaySchedulePlaceDao.java
  src/main/java/ddd/caffeine/ratrip/module/travel_plan/domain/repository/day_schedule/DaySchedulePlaceQueryRepository.java
  src/main/java/ddd/caffeine/ratrip/module/travel_plan/domain/repository/day_schedule/implementation/DaySchedulePlaceQueryRepositoryImpl.java
  src/main/java/ddd/caffeine/ratrip/module/travel_plan/domain/repository/implementation/TravelPlanUserQueryRepositoryImpl.java
  src/main/java/ddd/caffeine/ratrip/module/travel_plan/presentation/TravelPlanController.java
  src/main/java/ddd/caffeine/ratrip/module/travel_plan/presentation/dto/TravelPlanOngoingResponseDto.java
  src/main/java/ddd/caffeine/ratrip/module/travel_plan/presentation/dto/TravelPlanResponseDto.java
  src/main/java/ddd/caffeine/ratrip/module/travel_plan/presentation/dto/TravelPlanResponseModel.java
  src/main/java/ddd/caffeine/ratrip/module/travel_plan/presentation/dto/day_schedule/DayScheduleAddPlaceRequestDto.java
  src/main/java/ddd/caffeine/ratrip/module/travel_plan/presentation/dto/day_schedule/DayScheduleAddPlaceResponseDto.java
  src/main/java/ddd/caffeine/ratrip/module/travel_plan/presentation/dto/day_schedule/DayScheduleExchangePlaceOrderDto.java
  src/main/java/ddd/caffeine/ratrip/module/travel_plan/presentation/dto/day_schedule/DaySchedulePlaceDto.java
  src/test/java/ddd/caffeine/ratrip/module/travel_plan/domain/DaySchedulePlaceTest.java
Labels: enhancement

#55 구현한 API 리팩토링
  src/main/java/ddd/caffeine/ratrip/common/exception/ExceptionInformation.java
  src/main/java/ddd/caffeine/ratrip/module/place/application/BookmarkService.java
  src/main/java/ddd/caffeine/ratrip/module/place/application/BookmarkValidator.java
  src/main/java/ddd/caffeine/ratrip/module/place/application/PlaceService.java
  src/main/java/ddd/caffeine/ratrip/module/place/domain/Bookmark.java
  src/main/java/ddd/caffeine/ratrip/module/place/domain/repository/PlaceQueryRepository.java
  src/main/java/ddd/caffeine/ratrip/module/place/domain/repository/PlaceQueryRepositoryImpl.java
  src/main/java/ddd/caffeine/ratrip/module/place/domain/repository/PlaceRepository.java
  src/main/java/ddd/caffeine/ratrip/module/place/domain/repository/bookmark/BookmarkQueryRepository.java
  src/main/java/ddd/caffeine/ratrip/module/place/domain/repository/bookmark/BookmarkQueryRepositoryImpl.java
  src/main/java/ddd/caffeine/ratrip/module/place/domain/repository/bookmark/BookmarkRepository.java
  src/main/java/ddd/caffeine/ratrip/module/place/presentation/PlaceController.java
  src/main/java/ddd/caffeine/ratrip/module/place/presentation/dto/bookmark/BookmarkAddResponseDto.java
  src/main/java/ddd/caffeine/ratrip/module/place/presentation/dto/bookmark/BookmarkPlaceModel.java
  src/main/java/ddd/caffeine/ratrip/module/place/presentation/dto/bookmark/BookmarkPlaceResponseDto.java
  src/main/java/ddd/caffeine/ratrip/module/place/presentation/dto/bookmark/BookmarkResponseDto.java
  src/main/java/ddd/caffeine/ratrip/module/place/presentation/dto/detail/PlaceDetailsResponseDto.java
  src/main/java/ddd/caffeine/ratrip/module/place/presentation/dto/detail/PlaceSaveByThirdPartyRequestDto.java
  src/main/java/ddd/caffeine/ratrip/module/place/presentation/dto/detail/PlaceSaveThirdPartyResponseDto.java
  src/main/java/ddd/caffeine/ratrip/module/travel_plan/application/DaySchedulePlaceService.java
  src/main/java/ddd/caffeine/ratrip/module/travel_plan/application/TravelPlanService.java
  src/main/java/ddd/caffeine/ratrip/module/travel_plan/application/TravelPlanUserService.java
  src/main/java/ddd/caffeine/ratrip/module/travel_plan/domain/repository/day_schedule/DaySchedulePlaceQueryRepository.java
  src/main/java/ddd/caffeine/ratrip/module/travel_plan/domain/repository/day_schedule/implementation/DaySchedulePlaceQueryRepositoryImpl.java
  src/main/java/ddd/caffeine/ratrip/module/travel_plan/presentation/TravelPlanController.java
  src/main/java/ddd/caffeine/ratrip/module/travel_plan/presentation/dto/day_schedule/DayScheduleAddPlaceRequestDto.java
  src/main/java/ddd/caffeine/ratrip/module/travel_plan/presentation/dto/day_schedule/DayScheduleExchangePlaceOrderDto.java
  src/test/java/ddd/caffeine/ratrip/module/place/domain/repository/PlaceRepositoryTest.java
  src/test/java/ddd/caffeine/ratrip/module/place/domain/repository/bookmark/BookmarkRepositoryTest.java
  src/test/java/ddd/caffeine/ratrip/module/place/presentation/PlaceControllerTest.java
Labels: enhancement

#62 hotfix : swagger cors 문제
  src/main/java/ddd/caffeine/ratrip/common/configuration/SecurityConfiguration.java
Labels: hotfix

#64 hotfix : cors problem
  src/main/java/ddd/caffeine/ratrip/RatripServerApplication.java
  src/main/java/ddd/caffeine/ratrip/common/configuration/SwaggerConfiguration.java
Labels: hotfix

#65 일정 종료 API
  src/main/java/ddd/caffeine/ratrip/common/exception/ExceptionInformation.java
  src/main/java/ddd/caffeine/ratrip/module/travel_plan/application/TravelPlanService.java
  src/main/java/ddd/caffeine/ratrip/module/travel_plan/application/TravelPlanValidator.java
  src/main/java/ddd/caffeine/ratrip/module/travel_plan/domain/TravelPlan.java
  src/main/java/ddd/caffeine/ratrip/module/travel_plan/presentation/TravelPlanController.java
  src/main/java/ddd/caffeine/ratrip/module/travel_plan/presentation/dto/TravelPlanResponseModel.java
Labels: enhancement

#63 북마크 도메인 기본키 전략 변경 및 URI 리팩토링
  src/main/java/ddd/caffeine/ratrip/common/exception/ExceptionInformation.java
  src/main/java/ddd/caffeine/ratrip/module/place/application/BookmarkService.java
  src/main/java/ddd/caffeine/ratrip/module/place/application/BookmarkValidator.java
  src/main/java/ddd/caffeine/ratrip/module/place/application/PlaceService.java
  src/main/java/ddd/caffeine/ratrip/module/place/domain/bookmark/Bookmark.java
  src/main/java/ddd/caffeine/ratrip/module/place/domain/bookmark/BookmarkId.java
  src/main/java/ddd/caffeine/ratrip/module/place/domain/bookmark/repository/BookmarkQueryRepository.java
  src/main/java/ddd/caffeine/ratrip/module/place/domain/bookmark/repository/BookmarkQueryRepositoryImpl.java
  src/main/java/ddd/caffeine/ratrip/module/place/domain/bookmark/repository/BookmarkRepository.java
  src/main/java/ddd/caffeine/ratrip/module/place/domain/bookmark/repository/dao/BookMarkPlaceDao.java
  src/main/java/ddd/caffeine/ratrip/module/place/feign/naver/model/FeignImageModel.java
  src/main/java/ddd/caffeine/ratrip/module/place/presentation/PlaceController.java
  src/main/java/ddd/caffeine/ratrip/module/place/presentation/dto/PlaceDetailResponseDto.java
  src/main/java/ddd/caffeine/ratrip/module/place/presentation/dto/PlaceSaveThirdPartyResponseDto.java
  src/main/java/ddd/caffeine/ratrip/module/place/presentation/dto/bookmark/BookmarkPlaceModel.java
  src/main/java/ddd/caffeine/ratrip/module/place/presentation/dto/bookmark/BookmarkResponseDto.java
  src/test/java/ddd/caffeine/ratrip/module/place/domain/repository/bookmark/BookmarkRepositoryTest.java
Labels: enhancement

#67 장소 카테고리 & 마이페이지 변경된 요구사항 반영
  src/main/java/ddd/caffeine/ratrip/module/place/application/PlaceService.java
  src/main/java/ddd/caffeine/ratrip/module/place/domain/Place.java
  src/main/java/ddd/caffeine/ratrip/module/place/domain/sub_domain/Category.java
  src/main/java/ddd/caffeine/ratrip/module/place/feign/kakao/model/FeignPlaceData.java
  src/main/java/ddd/caffeine/ratrip/module/place/feign/kakao/model/FeignPlaceModel.java
  src/main/java/ddd/caffeine/ratrip/module/place/presentation/PlaceController.java
  src/main/java/ddd/caffeine/ratrip/module/place/presentation/dto/bookmark/BookmarkPlaceResponse.java
  src/main/java/ddd/caffeine/ratrip/module/place/presentation/dto/bookmark/BookmarkPlaceResponseDto.java
  src/main/java/ddd/caffeine/ratrip/module/place/presentation/dto/request/PlaceSaveByThirdPartyRequestDto.java
  src/main/java/ddd/caffeine/ratrip/module/place/presentation/dto/request/PlaceSearchRequestDto.java
  src/main/java/ddd/caffeine/ratrip/module/place/presentation/dto/response/PlaceDetailResponseDto.java
  src/main/java/ddd/caffeine/ratrip/module/place/presentation/dto/response/PlaceInRegionResponse.java
  src/main/java/ddd/caffeine/ratrip/module/place/presentation/dto/response/PlaceInRegionResponseDto.java
  src/main/java/ddd/caffeine/ratrip/module/place/presentation/dto/response/PlaceSaveThirdPartyResponseDto.java
  src/main/java/ddd/caffeine/ratrip/module/place/presentation/dto/response/PlaceSearchResponse.java
  src/main/java/ddd/caffeine/ratrip/module/place/presentation/dto/response/PlaceSearchResponseDto.java
  src/main/java/ddd/caffeine/ratrip/module/travel_plan/application/TravelPlanService.java
  src/main/java/ddd/caffeine/ratrip/module/travel_plan/application/TravelPlanUserService.java
  src/main/java/ddd/caffeine/ratrip/module/travel_plan/application/day_schedule/DaySchedulePlaceService.java
  src/main/java/ddd/caffeine/ratrip/module/travel_plan/application/day_schedule/DayScheduleService.java
  src/main/java/ddd/caffeine/ratrip/module/travel_plan/application/day_schedule/DayScheduleValidator.java
  src/main/java/ddd/caffeine/ratrip/module/travel_plan/domain/day_schedule/repository/DaySchedulePlaceQueryRepository.java
  src/main/java/ddd/caffeine/ratrip/module/travel_plan/domain/day_schedule/repository/implementation/DaySchedulePlaceQueryRepositoryImpl.java
  src/main/java/ddd/caffeine/ratrip/module/travel_plan/presentation/TravelPlanController.java
  src/main/java/ddd/caffeine/ratrip/module/travel_plan/presentation/dto/TravelPlanResponseDto.java
  src/main/java/ddd/caffeine/ratrip/module/travel_plan/presentation/dto/day_schedule/request/DayScheduleAddPlaceRequestDto.java
  src/main/java/ddd/caffeine/ratrip/module/travel_plan/presentation/dto/day_schedule/request/DayScheduleExchangePlaceSequenceDto.java
  src/main/java/ddd/caffeine/ratrip/module/travel_plan/presentation/dto/day_schedule/request/DayScheduleUpdatePlaceRequestDto.java
  src/main/java/ddd/caffeine/ratrip/module/travel_plan/presentation/dto/day_schedule/response/DayScheduleInTravelPlanResponse.java
  src/main/java/ddd/caffeine/ratrip/module/travel_plan/presentation/dto/day_schedule/response/DayScheduleInTravelPlanResponseDto.java
  src/main/java/ddd/caffeine/ratrip/module/travel_plan/presentation/dto/day_schedule/response/DaySchedulePlaceDto.java
  src/main/java/ddd/caffeine/ratrip/module/travel_plan/presentation/dto/day_schedule/response/DaySchedulePlaceResponseDto.java
  src/main/java/ddd/caffeine/ratrip/module/travel_plan/presentation/dto/day_schedule/response/DayScheduleResponseDto.java
  src/main/java/ddd/caffeine/ratrip/module/travel_plan/presentation/dto/day_schedule/response/PlaceModelInDaySchedule.java
  src/main/java/ddd/caffeine/ratrip/module/travel_plan/presentation/dto/request/TravelPlanInitRequestDto.java
  src/main/java/ddd/caffeine/ratrip/module/travel_plan/presentation/dto/response/MyTravelPlanResponse.java
  src/main/java/ddd/caffeine/ratrip/module/travel_plan/presentation/dto/response/MyTravelPlanResponseDto.java
  src/main/java/ddd/caffeine/ratrip/module/travel_plan/presentation/dto/response/TravelPlanOngoingResponseDto.java
  src/main/java/ddd/caffeine/ratrip/module/travel_plan/presentation/dto/response/TravelPlanRepresentativePhotoResponse.java
  src/main/java/ddd/caffeine/ratrip/module/travel_plan/presentation/dto/response/TravelPlanResponseDto.java
  src/test/java/ddd/caffeine/ratrip/module/place/domain/PlaceTest.java
  src/test/java/ddd/caffeine/ratrip/module/place/domain/repository/PlaceRepositoryTest.java
  src/test/java/ddd/caffeine/ratrip/module/place/domain/repository/bookmark/BookmarkRepositoryTest.java
  src/test/java/ddd/caffeine/ratrip/module/place/domain/sub_domain/CategoryTest.java
  src/test/java/ddd/caffeine/ratrip/module/place/presentation/PlaceControllerTest.java
Labels: enhancement

#66 계획이 끝난 여행계획 종료 스케쥴러
  src/main/java/ddd/caffeine/ratrip/RatripServerApplication.java
  src/main/java/ddd/caffeine/ratrip/module/travel_plan/application/TravelPlanService.java
  src/main/java/ddd/caffeine/ratrip/module/travel_plan/domain/repository/TravelPlanQueryRepository.java
  src/main/java/ddd/caffeine/ratrip/module/travel_plan/domain/repository/dao/LocalDateDao.java
  src/main/java/ddd/caffeine/ratrip/module/travel_plan/domain/repository/implementation/TravelPlanQueryRepositoryImpl.java
Labels: enhancement
